language: node_js
node_js:
  - 6
sudo: required
before_install:
  - npm install -g xo npx
env:
  global:
    - SEMANTIC_TAG=${OPENCV_INSTALL_PREFIX}

install:
  - npm install

script:
  - npm test

after_success:
  - npx -p node@8 -c "npm run semantic-release"

before_deploy:
    - echo $SEMANTIC_TAG
    - echo "test" 
deploy:
  - skip_cleanup: true
    provider: script
    script: bash ./scripts/test.sh $SEMANTIC_TAG
    on:
      branch: master
