language: node_js
node_js:
  - 6
sudo: required
before_install:
  - npm install -g xo npx
env:
  global:
    - SEMAN_TAG=${SEMANTIC_TAG}

install:
  - npm install

script:
  - npm test

after_success:
  - bash bash ./scripts/semantic.sh
  - echo $SEM_TAG
  - npm config set loglevel warn
  - npx -p node@8 -c "npm run semantic-release"

before_deploy:
    - echo $SEMAN_TAG
    - echo $SEMANTIC_TAG
    - echo ${SEMANTIC_TAG}
    - echo "test" 
deploy:
  - skip_cleanup: true
    provider: script
    script: bash ./scripts/test.sh $SEMANTIC_TAG
    on:
      branch: master
