language: node_js
node_js:
  - 6
sudo: required
before_install:
  - npm install -g xo npx

install:
  - npm install

script:
  - npm test

after_success:
  - npx -p node@8 -c "npm run semantic-release"

before_deploy: bash ./scripts/semantic.sh
deploy:
  - skip_cleanup: true
    provider: script
    script: bash ./scripts/test.sh $SEM_TAG
    on:
      branch: master
